# Generated by Django 5.1.2 on 2025-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('strong_against', models.ManyToManyField(blank=True, related_name='weak_against_me', to='champions.champion')),
                ('weak_against', models.ManyToManyField(blank=True, related_name='strong_against_me', to='champions.champion')),
            ],
        ),
    ]
